name: Continuous Integration and Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out âœŒâœŒ
        uses: actions/checkout@v2

      - name: Setup .NET 5ğŸ˜
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
        
      - name: Restore Dependencies âœŒ
        run: dotnet restore
      
      - name: Build appğŸ‘
        run: dotnet build -c Release --no-restore
          